package model;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;

/**
 * This class contains methods, attributes, and relations related with the CYK algorithm.
 * @version 1
 * @author Santiago Trochez Velasco, https://github.com/Santiagokmids <br>
 * @author Luis Miguel Ossa Arias, https://github.com/Itsumohitoride <br>
 */

public class AlgorithmCYK {

	Hashtable<String, Hashtable<String, String>> states;
	int numberStates;
	String string;
	int sizeString;
	String[][] cykMatrix;
	
	/**
	 * <b>name:</b> AlgorithmCYK <br>
	 * Create an object of the CYK algorithm. <br>
	 * <b>post:</b> An object of the CYK algorithm has created. <br>
	 */

	public AlgorithmCYK() {
		states = new Hashtable<>();
		numberStates = 0;
		sizeString = 0;
	}
	
	/**
	 * <b>name:</b> splitProductions <br>
	 * This method create the states with its productions. <br>
	 * <b>post:</b> a hashtable with all the information of the states and its productions has created. <br>
	 * @param text are the state's productions.
	 * @return <code>productionsOfState</code> is the hashtable with the state's productions.
	 */

	public Hashtable<String, String> splitProductions(String text){
		String [] splitProductions = text.split("/");

		Hashtable<String, String> productionsOfState = new Hashtable<>();

		for (int i = 0; i < splitProductions.length; i++) {
			productionsOfState.put(splitProductions[i],splitProductions[i]);
		}

		return productionsOfState;
	}
	
	/**
	 * <b>name:</b> addStates <br>
	 * This method add the split production into a hashtable. <br>
	 * <b>post:</b> the split productions are into the hashtable. <br>
	 * @param state is the state that is associated with the productions.
	 * @param productions are the productions that are associated with the state.
	 */

	public void addStates(String state, Hashtable<String, String> productions) {
		states.put(state, productions);
	}
	
	/**
	 * <b>name:</b> addString <br>
	 * Create the matrix cykMatrix with the string size. <br>
	 * <b>post:</b> the matrix cykMatrix has created. <br>
	 * @param string is the string that is going to be analyzed.
	 */

	public void addString(String string) {
		this.string = string;
		sizeString = this.string.length();
		cykMatrix = new String[sizeString][sizeString];
	}
	
	/**
	 * <b>name:</b> calculateCYK <br>
	 * Analyze the string and discover if it is generated by the grammar.
	 * <b>post:</b> the cyk algorithm has been implemented. <br>
	 * @return <code>verify</code> is the result of apply the cyk algorithm.
	 */

	public boolean calculateCYK() {
		stepOne();
		stepTwo();
		return (cykMatrix[0][sizeString-1]).contains("S");
	}
	
	/**
	 * <b>name:</b> searchSymbol <br>
	 * Search a production in a state. <br>
	 * <b>post:</b> determinate if a production is in a state. <br>
	 * @param symbol is the production to be sought.
	 * @return <code>state</code> is the state that contains the production.
	 */
	
	public String searchSymbol(String symbol) {
		
		Enumeration<Hashtable<String, String>> productions = states.elements();
		Enumeration<String> keys = states.keys();
		String state = ""; 
		String verify;
		while (productions.hasMoreElements()) {
			
			verify = productions.nextElement().get(symbol);
			String current = (String) keys.nextElement();
			
			if(verify != null && verify.equals(symbol)) {
				state += current;
			}
		}
		
		return state;
	}
	
	/**
	 * <b>name:</b> stepOne <br>
	 * Put the states that contains the terminals into the matrix. <br>
	 * <b>post:</b> The states are now in the matrix. <br>
	 */

	public void stepOne() {
		
		String[] symbol = string.split("");
		
		for (int i = 0; i < sizeString; i++) {
			cykMatrix[i][0] = searchSymbol(symbol[i]);
		}
	}
	
	/**
	 * <b>name:</b> stepTwo <br>
	 * Put the states in the rest of the matrix.
	 * <b>post:</b> the matrix is filled with all states. <br>
	 */

	public void stepTwo() {
		
		String states1 = "";
		String states2 = "";

		for (int j = 1; j < sizeString; j++) {
			
			for (int i = 0; i <= sizeString - (j+2) + 1; i++) {
				
				String combination = "";
				
				boolean verify = true;
				
				for (int k = 1; k < (j+2) - 1; k++) {
					verify = false;
					states1 = cykMatrix[i][k-1];
					states2 = cykMatrix[i+k][j-k];
					combination += combinations(states1, states2);
				}
				
				if(!verify) {
					cykMatrix[i][j] = combination;
				}
			}
		}
	}
	
	/**
	 * <b>name:</b> combinations <br>
	 * Generates the necessary combinations between two sets. <br>
	 * <b>post:</b> The combinations were made. <br>
	 * @param states1 is the first set.
	 * @param states2 is the second set.
	 * @return <code>symbol</code> is the set's combinations.
	 */
	
	public String combinations(String states1, String states2) {
		String[] first = states1.split("");
		String[] second = states2.split("");
		
		ArrayList<String> combinations = new ArrayList<>();
		
		for (int i = 0; i < first.length; i++) {
			
			for (int j = 0; j < second.length; j++) {
				combinations.add(first[i]+second[j]);
			}
		}
		String symbol = "";
		
		for (int i = 0; i < combinations.size(); i++) {
			symbol += searchSymbol(combinations.get(i));
		}
		
		return symbol;
	}
}
